[package]
name = "adaptor"
version = "0.1.0"
edition = "2021"

[dependencies]

musig2 = "0.2.0"
rand = "0.8.5"
secp = { version = "0.4.1", features = ["rand"] }
bdk = "0.29.0"
anyhow = "1.0.93"
dotenv = "0.15.0"
